[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  bin = "./tmp/main.exe"
  include_ext = ["go", "env"]
  exclude_dir = ["tmp"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
